event_flags:
  '2017':
  - goodVertices
  - globalSuperTightHalo2016Filter
  - HBHENoiseFilter
  - HBHENoiseIsoFilter
  - EcalDeadCellTriggerPrimitiveFilter
  - BadPFMuonFilter
  - BadPFMuonDzFilter
  - ecalBadCalibFilter
