object_preselection:
    FatJet:
        dr_lepton: 0.8
        pt: 200
        eta: 2.4
        mass: {low: 50, high: 200}
        jetId: 2
    Jet:
        dr_lepton: 0.4
        pt: 30
        eta: 2.4
        jetId: 2
        puId:
          wp: L
          value: 4
          maxpt: 50.0
    btag:
        tagger: btagDeepFlavB
        wp: 0.3040
