skim_params:
    Jet:
        dr_lepton: 0.4
        pt: 30
        eta: 2.4
        jetId: 2
        puId:
          wp: L
          value: 4
          maxpt: 50.0
    Electron:
        pt: 30
        eta: 2.5
        sip3d: 4
        cutBasedNoIso: 4
        softCutBasedNoIso: 1
        iso: 0.1
    Muon:
        pt: 30
        eta: 2.4
        id: 1
        softId: 1
        sip3d: 4
        iso: 0.2
