plotting_style:
  opts_mc:
    stack: False
      #histtype: "step"
  
  samples_groups:
    ttbb (4FS):
      - TTbb_Hadronic__tt+B
      - TTbb_SemiLeptonic__tt+B
      - TTbb_2L2Nu__tt+B
    TTBar (5FS):
      - TTToSemiLeptonic__tt+LF
      - TTToSemiLeptonic__tt+C
      - TTTo2L2Nu__tt+LF
      - TTTo2L2Nu__tt+C
      - TTToHadronic__tt+LF
      - TTToHadronic__tt+C
    ttH:
      - ttHTobb__genMatch
      - ttHToNonbb__genMatch
      - ttHTobb__non_genMatch
      - ttHToNonbb__non_genMatch
    ttZ:
      - TTZToQQ__genMatch
      - TTZToLLNuNu__genMatch
      - TTZToBB__genMatch
      - TTZToQQ__non_genMatch
      - TTZToBB__non_genMatch
      - TTZToLLNuNu__non_genMatch
  exclude_samples:
    - TTToSemiLeptonic
    - TTbb_SemiLeptonic
    - TTToHadronic
    - TTbb_Hadronic
    - TTTo2L2Nu
    - TTbb_2L2Nu
    - TTToSemiLeptonic__tt+B
    - TTbb_SemiLeptonic__tt+C
    - TTbb_SemiLeptonic__tt+LF
    - TTToHadronic__tt+B
    - TTbb_Hadronic__tt+C
    - TTbb_Hadronic__tt+LF
    - TTTo2L2Nu__tt+B
    - TTbb_2L2Nu__tt+C
    - TTbb_2L2Nu__tt+LF
